import os

import psycopg2
from psycopg2.extras import RealDictCursor
from psycopg2_pool import ThreadSafeConnectionPool
from dotenv import load_dotenv

load_dotenv()


DATABASE_URL = os.getenv("DATABASE_URL")


# PostgreSQL connection pool
connection_pool = None


def get_connection():

    global connection_pool

    if not DATABASE_URL:
        raise ValueError("DATABASE_URL is not set in the .env file.")

    if connection_pool is None:

        connection_pool = ThreadSafeConnectionPool(
            minconn=1,
            maxconn=5,
            dsn=DATABASE_URL,
            cursor_factory=RealDictCursor
        )

    return connection_pool.getconn()


def release_connection(connection):
    global connection_pool

    if connection_pool is not None:
        connection_pool.putconn(connection)


def create_database():

    connection = get_connection()

    cursor = connection.cursor()

    # -------------------------------------------------
    # Users table
    # -------------------------------------------------

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users (

            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            name TEXT NOT NULL,

            email TEXT UNIQUE NOT NULL,

            password TEXT NOT NULL,

            role TEXT DEFAULT 'user'

        )
    """)


    # -------------------------------------------------
    # Password reset tokens table
    # -------------------------------------------------

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS password_reset_tokens (

            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            user_id INTEGER NOT NULL,

            token TEXT UNIQUE NOT NULL,

            expires_at TEXT NOT NULL,

            used INTEGER DEFAULT 0,

            FOREIGN KEY (user_id)
                REFERENCES users(id)

        )
    """)


    # -------------------------------------------------
    # Invoices table
    # -------------------------------------------------

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS invoices (

            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            user_id INTEGER,

            invoice_number TEXT,

            customer_name TEXT NOT NULL,

            customer_email TEXT NOT NULL,

            invoice_date TEXT NOT NULL,

            subtotal DOUBLE PRECISION NOT NULL,

            gst DOUBLE PRECISION NOT NULL,

            grand_total DOUBLE PRECISION NOT NULL,

            deleted INTEGER DEFAULT 0,

            deleted_at TEXT,

            FOREIGN KEY (user_id)
                REFERENCES users(id),

            UNIQUE(user_id, invoice_number)

        )
    """)

    cursor.execute("""
        ALTER TABLE invoices
        ADD COLUMN IF NOT EXISTS pdf_public_id TEXT
    """)


    # -------------------------------------------------
    # Invoice items table
    # -------------------------------------------------

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS invoice_items (

            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            invoice_id INTEGER,

            product_name TEXT NOT NULL,

            quantity INTEGER NOT NULL,

            price DOUBLE PRECISION NOT NULL,

            total DOUBLE PRECISION NOT NULL,

            FOREIGN KEY (invoice_id)
                REFERENCES invoices(id)

        )
    """)


    # -------------------------------------------------
    # Invoice counters table
    # -------------------------------------------------

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS invoice_counters (

            user_id INTEGER PRIMARY KEY,

            last_invoice_number INTEGER NOT NULL DEFAULT 0,

            FOREIGN KEY (user_id)
                REFERENCES users(id)

        )
    """)


    # -------------------------------------------------
    # Activity logs table
    # -------------------------------------------------

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS activity_logs (

            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            user_id INTEGER,

            action TEXT NOT NULL,

            description TEXT NOT NULL,

            created_at TEXT DEFAULT CURRENT_TIMESTAMP,

            FOREIGN KEY (user_id)
                REFERENCES users(id)

        )
    """)


    connection.commit()

    cursor.close()

    release_connection(connection)

    print("PostgreSQL database initialized successfully!")

    # =========================================================
# INVOICE FUNCTIONS
# =========================================================


def save_invoice(
    user_id,
    invoice_number,
    customer_name,
    customer_email,
    invoice_date,
    subtotal,
    gst,
    grand_total,
    product_names,
    quantities,
    prices
):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        # Insert invoice
        cursor.execute("""
            INSERT INTO invoices (
                user_id,
                invoice_number,
                customer_name,
                customer_email,
                invoice_date,
                subtotal,
                gst,
                grand_total
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id
        """, (
            user_id,
            invoice_number,
            customer_name,
            customer_email,
            invoice_date,
            subtotal,
            gst,
            grand_total
        ))

        invoice_id = cursor.fetchone()["id"]

        # Insert invoice items
        for product_name, quantity, price in zip(
            product_names,
            quantities,
            prices
        ):

            total = float(quantity) * float(price)

            cursor.execute("""
                INSERT INTO invoice_items (
                    invoice_id,
                    product_name,
                    quantity,
                    price,
                    total
                )
                VALUES (%s, %s, %s, %s, %s)
            """, (
                invoice_id,
                product_name,
                quantity,
                price,
                total
            ))

        connection.commit()

        print("Invoice saved to database!")

        return invoice_id

    except Exception:

        connection.rollback()

        raise

    finally:

        cursor.close()
        release_connection(connection)


def get_all_invoices(user_id):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT
                id,
                invoice_number,
                customer_name,
                customer_email,
                invoice_date,
                subtotal,
                gst,
                grand_total
            FROM invoices
            WHERE user_id = %s
              AND deleted = 0
            ORDER BY id DESC
        """, (user_id,))

        return cursor.fetchall()

    finally:

        cursor.close()
        release_connection(connection)


def get_deleted_invoices(user_id):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT
                id,
                invoice_number,
                customer_name,
                customer_email,
                invoice_date,
                subtotal,
                gst,
                grand_total,
                deleted_at
            FROM invoices
            WHERE user_id = %s
              AND deleted = 1
            ORDER BY deleted_at DESC
        """, (user_id,))

        return cursor.fetchall()

    finally:

        cursor.close()
        release_connection(connection)


def restore_invoice(invoice_id, user_id):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            UPDATE invoices
            SET
                deleted = 0,
                deleted_at = NULL
            WHERE id = %s
              AND user_id = %s
              AND deleted = 1
        """, (
            invoice_id,
            user_id
        ))

        connection.commit()

        print("Invoice restored successfully!")

    except Exception:

        connection.rollback()

        raise

    finally:

        cursor.close()
        release_connection(connection)


def permanently_delete_invoice(invoice_id, user_id):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        # Delete invoice items first
        cursor.execute("""
            DELETE FROM invoice_items
            WHERE invoice_id = %s
              AND invoice_id IN (
                  SELECT id
                  FROM invoices
                  WHERE id = %s
                    AND user_id = %s
                    AND deleted = 1
              )
        """, (
            invoice_id,
            invoice_id,
            user_id
        ))

        # Delete invoice
        cursor.execute("""
            DELETE FROM invoices
            WHERE id = %s
              AND user_id = %s
              AND deleted = 1
        """, (
            invoice_id,
            user_id
        ))

        connection.commit()

        print("Invoice permanently deleted!")

    except Exception:

        connection.rollback()

        raise

    finally:

        cursor.close()
        release_connection(connection)


def get_invoice_details(invoice_id, user_id):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT *
            FROM invoices
            WHERE id = %s
              AND user_id = %s
              AND deleted = 0
        """, (
            invoice_id,
            user_id
        ))

        invoice = cursor.fetchone()

        if invoice is None:
            return None, []

        cursor.execute("""
            SELECT *
            FROM invoice_items
            WHERE invoice_id = %s
        """, (invoice_id,))

        items = cursor.fetchall()

        return invoice, items

    finally:

        cursor.close()
        release_connection(connection)


def delete_invoice(invoice_id, user_id):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            UPDATE invoices
            SET
                deleted = 1,
                deleted_at = CURRENT_TIMESTAMP::TEXT
            WHERE id = %s
              AND user_id = %s
        """, (
            invoice_id,
            user_id
        ))

        connection.commit()

        print("Invoice moved to trash!")

    except Exception:

        connection.rollback()

        raise

    finally:

        cursor.close()
        release_connection(connection)

# =========================================================
# INVOICE STATISTICS
# =========================================================


def get_invoice_statistics(user_id):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT
                COUNT(*) AS total_invoices,
                COALESCE(SUM(grand_total), 0) AS total_revenue,
                COALESCE(SUM(gst), 0) AS total_gst,
                COALESCE(AVG(grand_total), 0) AS average_invoice
            FROM invoices
            WHERE user_id = %s
              AND deleted = 0
        """, (user_id,))

        return cursor.fetchone()

    finally:

        cursor.close()
        release_connection(connection)


def get_monthly_statistics(user_id):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT
                SUBSTRING(invoice_date, 4, 7) AS month,
                COUNT(*) AS total_invoices,
                SUM(grand_total) AS total_revenue
            FROM invoices
            WHERE user_id = %s
              AND deleted = 0
            GROUP BY
                SUBSTRING(invoice_date, 4, 7),
                SUBSTRING(invoice_date, 7, 4),
                SUBSTRING(invoice_date, 4, 2)
            ORDER BY
                SUBSTRING(invoice_date, 7, 4),
                SUBSTRING(invoice_date, 4, 2)
        """, (user_id,))

        return cursor.fetchall()

    finally:

        cursor.close()
        release_connection(connection)


def get_product_statistics(user_id):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT
                invoice_items.product_name,
                SUM(invoice_items.quantity) AS total_quantity,
                SUM(invoice_items.total) AS total_sales
            FROM invoice_items
            JOIN invoices
                ON invoice_items.invoice_id = invoices.id
            WHERE invoices.user_id = %s
              AND invoices.deleted = 0
            GROUP BY invoice_items.product_name
            ORDER BY total_quantity DESC
        """, (user_id,))

        return cursor.fetchall()

    finally:

        cursor.close()
        release_connection(connection)


# =========================================================
# USER / AUTHENTICATION FUNCTIONS
# =========================================================


def create_user(name, email, password):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            INSERT INTO users (
                name,
                email,
                password
            )
            VALUES (%s, %s, %s)
        """, (
            name,
            email,
            password
        ))

        connection.commit()

        print("User created successfully!")

    except Exception:

        connection.rollback()

        raise

    finally:

        cursor.close()
        release_connection(connection)


def get_user_by_email(email):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT *
            FROM users
            WHERE email = %s
        """, (email,))

        return cursor.fetchone()

    finally:

        cursor.close()
        release_connection(connection)


def create_password_reset_token(
    user_id,
    token,
    expires_at
):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            INSERT INTO password_reset_tokens (
                user_id,
                token,
                expires_at
            )
            VALUES (%s, %s, %s)
        """, (
            user_id,
            token,
            expires_at
        ))

        connection.commit()

    except Exception:

        connection.rollback()

        raise

    finally:

        cursor.close()
        release_connection(connection)


def get_password_reset_token(token):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT *
            FROM password_reset_tokens
            WHERE token = %s
        """, (token,))

        return cursor.fetchone()

    finally:

        cursor.close()
        release_connection(connection)


def mark_reset_token_used(token):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            UPDATE password_reset_tokens
            SET used = 1
            WHERE token = %s
        """, (token,))

        connection.commit()

    except Exception:

        connection.rollback()

        raise

    finally:

        cursor.close()
        release_connection(connection)


def update_user_password(user_id, hashed_password):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            UPDATE users
            SET password = %s
            WHERE id = %s
        """, (
            hashed_password,
            user_id
        ))

        connection.commit()

    except Exception:

        connection.rollback()

        raise

    finally:

        cursor.close()
        release_connection(connection)


# =========================================================
# ADMIN STATISTICS
# =========================================================


def get_total_users():

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT COUNT(*) AS total_users
            FROM users
        """)

        return cursor.fetchone()["total_users"]

    finally:

        cursor.close()
        release_connection(connection)


def get_total_invoices():

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT COUNT(*) AS total_invoices
            FROM invoices
            WHERE deleted = 0
        """)

        return cursor.fetchone()["total_invoices"]

    finally:

        cursor.close()
        release_connection(connection)


def get_total_revenue():

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT COALESCE(SUM(grand_total), 0) AS total_revenue
            FROM invoices
            WHERE deleted = 0
        """)

        return cursor.fetchone()["total_revenue"]

    finally:

        cursor.close()
        release_connection(connection)

# =========================================================
# ADMIN USER MANAGEMENT
# =========================================================


def get_all_users():

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT
                users.id,
                users.name,
                users.email,
                users.role,
                COUNT(invoices.id) AS invoice_count,
                COALESCE(SUM(invoices.grand_total), 0) AS total_revenue
            FROM users

            LEFT JOIN invoices
                ON users.id = invoices.user_id
                AND invoices.deleted = 0

            GROUP BY
                users.id,
                users.name,
                users.email,
                users.role

            ORDER BY users.id DESC
        """)

        return cursor.fetchall()

    finally:

        cursor.close()
        release_connection(connection)


def get_all_invoices_admin():

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT
                invoices.id,
                invoices.invoice_number,
                invoices.customer_name,
                invoices.customer_email,
                invoices.invoice_date,
                invoices.grand_total,
                users.name AS user_name,
                users.email AS user_email
            FROM invoices

            LEFT JOIN users
                ON invoices.user_id = users.id

            ORDER BY invoices.id DESC
        """)

        return cursor.fetchall()

    finally:

        cursor.close()
        release_connection(connection)


def get_recent_invoices(limit=5):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT
                invoices.invoice_number,
                invoices.customer_name,
                invoices.invoice_date,
                invoices.grand_total,
                users.name AS user_name
            FROM invoices

            LEFT JOIN users
                ON invoices.user_id = users.id

            WHERE invoices.deleted = 0

            ORDER BY invoices.id DESC

            LIMIT %s
        """, (limit,))

        return cursor.fetchall()

    finally:

        cursor.close()
        release_connection(connection)


def update_user_name(user_id, new_name):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            UPDATE users
            SET name = %s
            WHERE id = %s
        """, (
            new_name,
            user_id
        ))

        connection.commit()

        print("User name updated successfully!")

    except Exception:

        connection.rollback()

        raise

    finally:

        cursor.close()
        release_connection(connection)


def get_admin_count():

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT COUNT(*) AS admin_count
            FROM users
            WHERE role = 'admin'
        """)

        return cursor.fetchone()["admin_count"]

    finally:

        cursor.close()
        release_connection(connection)


def get_normal_user_count():

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT COUNT(*) AS normal_user_count
            FROM users
            WHERE role = 'user'
        """)

        return cursor.fetchone()["normal_user_count"]

    finally:

        cursor.close()
        release_connection(connection)


def get_user_details_admin(user_id):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT
                users.id,
                users.name,
                users.email,
                users.role,
                COUNT(invoices.id) AS invoice_count,
                COALESCE(SUM(invoices.grand_total), 0) AS total_revenue
            FROM users

            LEFT JOIN invoices
                ON users.id = invoices.user_id
                AND invoices.deleted = 0

            WHERE users.id = %s

            GROUP BY
                users.id,
                users.name,
                users.email,
                users.role
        """, (user_id,))

        return cursor.fetchone()

    finally:

        cursor.close()
        release_connection(connection)


def get_invoice_details_admin(invoice_id):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT
                invoices.id,
                invoices.invoice_number,
                invoices.customer_name,
                invoices.customer_email,
                invoices.invoice_date,
                invoices.subtotal,
                invoices.gst,
                invoices.grand_total,
                invoices.deleted,
                invoices.deleted_at,
                users.name AS user_name,
                users.email AS user_email
            FROM invoices

            LEFT JOIN users
                ON invoices.user_id = users.id

            WHERE invoices.id = %s
        """, (invoice_id,))

        invoice = cursor.fetchone()

        if invoice is None:
            return None

        cursor.execute("""
            SELECT
                product_name,
                quantity,
                price,
                total
            FROM invoice_items
            WHERE invoice_id = %s
        """, (invoice_id,))

        items = cursor.fetchall()

        return {
            "invoice": invoice,
            "items": items
        }

    finally:

        cursor.close()
        release_connection(connection)

# =========================================================
# ACCOUNT MANAGEMENT
# =========================================================


def delete_user_account(user_id):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        # Delete invoice items first
        cursor.execute("""
            DELETE FROM invoice_items
            WHERE invoice_id IN (
                SELECT id
                FROM invoices
                WHERE user_id = %s
            )
        """, (user_id,))

        # Delete invoices
        cursor.execute("""
            DELETE FROM invoices
            WHERE user_id = %s
        """, (user_id,))

        # Delete password reset tokens
        cursor.execute("""
            DELETE FROM password_reset_tokens
            WHERE user_id = %s
        """, (user_id,))

        # Delete invoice counter
        cursor.execute("""
            DELETE FROM invoice_counters
            WHERE user_id = %s
        """, (user_id,))

        # Delete activity logs
        cursor.execute("""
            DELETE FROM activity_logs
            WHERE user_id = %s
        """, (user_id,))

        # Finally delete the user
        cursor.execute("""
            DELETE FROM users
            WHERE id = %s
        """, (user_id,))

        connection.commit()

        print("User account deleted successfully!")

    except Exception:

        connection.rollback()

        raise

    finally:

        cursor.close()
        release_connection(connection)


# =========================================================
# ACTIVITY LOG FUNCTIONS
# =========================================================


def log_activity(user_id, action, description):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            INSERT INTO activity_logs (
                user_id,
                action,
                description
            )
            VALUES (%s, %s, %s)
        """, (
            user_id,
            action,
            description
        ))

        connection.commit()

    except Exception:

        connection.rollback()

        raise

    finally:

        cursor.close()
        release_connection(connection)


def get_recent_activity(limit=20):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            SELECT
                activity_logs.id,
                activity_logs.action,
                activity_logs.description,
                activity_logs.created_at,
                users.name AS user_name,
                users.email AS user_email
            FROM activity_logs

            LEFT JOIN users
                ON activity_logs.user_id = users.id

            ORDER BY activity_logs.id DESC

            LIMIT %s
        """, (limit,))

        return cursor.fetchall()

    finally:

        cursor.close()
        release_connection(connection)

def update_invoice_pdf_public_id(invoice_id, pdf_public_id):

    connection = get_connection()
    cursor = connection.cursor()

    try:

        cursor.execute("""
            UPDATE invoices
            SET pdf_public_id = %s
            WHERE id = %s
        """, (
            pdf_public_id,
            invoice_id
        ))

        connection.commit()

    except Exception:

        connection.rollback()

        raise

    finally:

        cursor.close()
        release_connection(connection)